name = "Breathing"

[[params]]
name = "color"
label = "Color"
[params.control]
type = "color"
[params.default]
type = "color"
value = {r = 255, g = 255, b = 255}

[[params]]
name = "speed"
label = "Speed"
[params.control]
type = "slider"
min = 0.005
max = 0.2
step = 0.005
[params.default]
type = "number"
value = 0.03

[[params]]
name = "min_brightness"
label = "Min Brightness"
[params.control]
type = "slider"
min = 0.0
max = 0.9
step = 0.05
[params.default]
type = "number"
value = 0.0

[script]
code = "dim(color, min_brightness + (1.0 - min_brightness) * wave(time * speed))"
