[package]
name = "mqtt"
version = "0.1.0"
edition = "2024"

[dependencies]
application = { workspace = true }
domain      = { workspace = true }
effects     = { workspace = true }
store       = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
tokio       = { workspace = true, features = ["time"] }
rumqttc     = "0.24"

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
sqlx  = { workspace = true }
