[led_controller]
controller_type = "console"
pixel_count = 100
spi_path = "/dev/spidev0.0"
freq_hz = 1000000
latch_time_micros = 500
crossfade_ms = 300

[server]
ip_address = "127.0.0.1"
port = 5000

[mdns]
enable = true
port = 5353
name = "LumeHub"

[effects]
presets = {}

[mqtt]
enabled = false
host = "localhost"
port = 1883
device_id = "lumehub"
topic_prefix = "lumehub"
ha_discovery = true
ha_discovery_prefix = "homeassistant"
# [mqtt]
# enabled = true
# host = "192.168.178.145"
# port = 1883
